import { createFileRoute } from '@tanstack/react-router';
import { useServerFn } from '@tanstack/react-start';
import { useState } from 'react';
import { Plus } from 'lucide-react';
import { Kerangka, Daftar } from '@/components/kerangka';
import { Button } from '@/components/ui/button';
import { LencanaTeks } from '@/components/status-kamar';
import { useTable, type Employee } from '@/lib/data-live';
import { createEmployee, manageEmployee } from '@/lib/employee.functions';
import { meta } from '@/lib/meta';
export const Route=createFileRoute('/karyawan')({head:()=>meta('Karyawan','Daftar petugas Baturaden 25 Homestay.'),component:Halaman});
function Halaman(){const {rows,refresh,error}=useTable('employees');const create=useServerFn(createEmployee);const manage=useServerFn(manageEmployee);const [item,setItem]=useState<Employee|null>(null);const [open,setOpen]=useState(false);const [name,setName]=useState('');const [employeeId,setEmployeeId]=useState('');const [email,setEmail]=useState('');const [position,setPosition]=useState<'receptionist'|'housekeeping'>('receptionist');const [active,setActive]=useState(true);const [password,setPassword]=useState('');const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);
 function edit(k?:Employee){setItem(k??null);setName(k?.name??'');setEmployeeId(k?.employee_id??'');setEmail('');setPosition(k?.position??'receptionist');setActive(k?.active??true);setPassword('');setMessage('');setOpen(true)}
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);try{if(item)await manage({data:{id:item.id,name,position,active,...(password ? { password } : {})}});else await create({data:{name,employeeId,email,password,position}});setOpen(false);await refresh()}catch(err){setMessage(err instanceof Error?err.message:'Tidak dapat menyimpan karyawan.')}finally{setBusy(false)}}
 return <Kerangka judul="Karyawan" keterangan={`${rows.length} karyawan`} aksi={<Button className="h-11 rounded-xl" onClick={()=>edit()}><Plus/>Tambah</Button>}>{error&&<p role="alert">{error}</p>}<Daftar>{rows.map(k=><li key={k.id} className="flex items-center gap-3 px-4 py-3.5"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-full bg-primary-soft text-sm font-bold text-primary">{k.name[0]}</span><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{k.name}</p><p className="text-xs text-muted-foreground">{k.employee_id} · {k.position==='receptionist'?'Resepsionis':'Petugas Kebersihan'}</p></div><LencanaTeks status={k.active?'Aktif':'Tidak Aktif'}/><Button size="sm" variant="outline" onClick={()=>edit(k)}>Ubah</Button></li>)}</Daftar>{open&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-foreground/30 p-4"><form onSubmit={save} className="w-full max-w-md space-y-3 rounded-2xl bg-background p-5 shadow-lembut"><h2 className="text-lg font-bold">{item?'Ubah karyawan':'Tambah karyawan'}</h2><label className="block text-sm">Nama<input required value={name} onChange={e=>setName(e.target.value)} className="mt-1 h-11 w-full rounded-xl border border-input bg-background px-3"/></label>{!item&&<><label className="block text-sm">Nomor karyawan<input required value={employeeId} onChange={e=>setEmployeeId(e.target.value)} className="mt-1 h-11 w-full rounded-xl border border-input bg-background px-3"/></label><label className="block text-sm">Email<input required type="email" value={email} onChange={e=>setEmail(e.target.value)} className="mt-1 h-11 w-full rounded-xl border border-input bg-background px-3"/></label></>}<label className="block text-sm">Posisi<select value={position} onChange={e=>setPosition(e.target.value as typeof position)} className="mt-1 h-11 w-full rounded-xl border border-input bg-background px-3"><option value="receptionist">Resepsionis</option><option value="housekeeping">Petugas Kebersihan</option></select></label><label className="block text-sm">{item?'Atur ulang kata sandi (opsional)':'Kata sandi'}<input type="password" minLength={8} required={!item} value={password} onChange={e=>setPassword(e.target.value)} className="mt-1 h-11 w-full rounded-xl border border-input bg-background px-3"/></label>{item&&<label className="flex gap-2 text-sm"><input type="checkbox" checked={active} onChange={e=>setActive(e.target.checked)}/>Aktif</label>}{message&&<p role="alert" className="text-sm text-destructive">{message}</p>}<div className="flex justify-end gap-2"><Button type="button" variant="outline" onClick={()=>setOpen(false)}>Batal</Button><Button disabled={busy}>Simpan</Button></div></form></div>}</Kerangka>}
