import { createFileRoute } from '@tanstack/react-router';
import { useState } from 'react';
import { Kerangka, Daftar } from '@/components/kerangka';
import { Button } from '@/components/ui/button';
import { useTable, type Package } from '@/lib/data-live';
import { rupiah } from '@/lib/data-contoh';
import { supabase } from '@/integrations/supabase/client';
import { meta } from '@/lib/meta';
export const Route=createFileRoute('/paket')({head:()=>meta('Paket dan Harga','Pengelolaan paket menginap Baturaden 25 Homestay.'),component:Halaman});
function Halaman(){const {rows,refresh,error}=useTable('packages');const history=useTable('package_price_history');const [item,setItem]=useState<Package|null>(null);const [open,setOpen]=useState(false);const [nama,setNama]=useState('');const [durasi,setDurasi]=useState('120');const [harga,setHarga]=useState('0');const [alasan,setAlasan]=useState('');const [deskripsi,setDeskripsi]=useState('');const [active,setActive]=useState(true);const [message,setMessage]=useState('');
 function edit(p?:Package){setItem(p??null);setNama(p?.name??'');setDurasi(String(p?.duration_minutes??120));setHarga(String(p?.price??0));setDeskripsi(p?.description??'');setActive(p?.active??true);setAlasan('');setMessage('');setOpen(true)}
 async function save(e:React.FormEvent){e.preventDefault();if(!nama.trim()||Number(durasi)<=0||Number(harga)<0){setMessage('Periksa nama, durasi, dan harga paket.');return}if(item&&Number(item.price)!==Number(harga)&&!alasan.trim()){setMessage('Isi alasan perubahan harga.');return}const payload={name:nama.trim(),duration_minutes:Number(durasi),price:Number(harga),description:deskripsi,active};const result=item?await supabase.from('packages').update(payload).eq('id',item.id):await supabase.from('packages').insert(payload);if(result.error)setMessage(result.error.message);else{setOpen(false);await refresh();await history.refresh()}}
 return <Kerangka judul="Paket & Harga" aksi={<Button className="h-11 rounded-xl" onClick={()=>edit()}>Tambah</Button>}>{error&&<p role="alert">{error}</p>}<Daftar>{rows.map(p=><li key={p.id} className="flex items-center gap-3 px-4 py-4"><div className="min-w-0 flex-1"><p className="text-sm font-semibold">{p.name}</p><p className="text-xs text-muted-foreground">{p.duration_minutes} menit · {p.active?'Aktif':'Tidak aktif'}</p></div><span className="text-sm font-bold">{rupiah(Number(p.price))}</span><Button size="sm" variant="outline" onClick={()=>edit(p)}>Ubah</Button></li>)}</Daftar><h2 className="mt-8 mb-3 text-xs font-semibold uppercase text-muted-foreground">Riwayat harga</h2><Daftar>{history.rows.map(h=><li key={h.id} className="px-4 py-3 text-sm">{rows.find(p=>p.id===h.package_id)?.name??'Paket'} · {rupiah(Number(h.old_price))} → {rupiah(Number(h.new_price))}<p className="text-xs text-muted-foreground">{h.reason} · {new Date(h.changed_at).toLocaleDateString('id-ID')}</p></li>)}</Daftar>{open&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-foreground/30 p-4"><form onSubmit={save} className="w-full max-w-md space-y-3 rounded-2xl bg-background p-5 shadow-lembut"><h2 className="text-lg font-bold">{item?'Ubah paket':'Tambah paket'}</h2>{[['Nama paket',nama,setNama],['Durasi (menit)',durasi,setDurasi],['Harga',harga,setHarga],['Deskripsi',deskripsi,setDeskripsi]].map(([label,value,setter])=><label key={label as string} className="block text-sm">{label as string}<input required={label!=='Deskripsi'} type={label==='Durasi (menit)'||label==='Harga'?'number':'text'} min={label==='Durasi (menit)'?'1':label==='Harga'?'0':undefined} value={value as string} onChange={e=>(setter as (s:string)=>void)(e.target.value)} className="mt-1 h-11 w-full rounded-xl border border-input bg-background px-3"/></label>)}{item&&Number(item.price)!==Number(harga)&&<label className="block text-sm">Alasan perubahan harga<input required value={alasan} onChange={e=>setAlasan(e.target.value)} className="mt-1 h-11 w-full rounded-xl border border-input bg-background px-3"/></label>}<label className="flex gap-2 text-sm"><input type="checkbox" checked={active} onChange={e=>setActive(e.target.checked)}/>Aktif</label>{message&&<p role="alert" className="text-sm text-destructive">{message}</p>}<div className="flex justify-end gap-2"><Button type="button" variant="outline" onClick={()=>setOpen(false)}>Batal</Button><Button>Simpan</Button></div></form></div>}</Kerangka>}
