import { createFileRoute } from '@tanstack/react-router';
import { useState } from 'react';
import { Kerangka, Daftar, KotakCari } from '@/components/kerangka';
import { Button } from '@/components/ui/button';
import { useTable, type Guest } from '@/lib/data-live';
import { supabase } from '@/integrations/supabase/client';
import { meta } from '@/lib/meta';
export const Route = createFileRoute('/tamu')({head:()=>meta('Tamu','Data tamu dan pencarian nama atau nomor HP Baturaden 25 Homestay.'),component:HalamanTamu});
function HalamanTamu(){const {rows,loading,error,refresh}=useTable('guests'); const [cari,setCari]=useState('');const [open,setOpen]=useState(false);const [editing,setEditing]=useState<Guest|null>(null);const [nama,setNama]=useState('');const [alamat,setAlamat]=useState('');const [telepon,setTelepon]=useState('');const [catatan,setCatatan]=useState('');const [message,setMessage]=useState('');const hasil=rows.filter(t=>t.full_name.toLowerCase().includes(cari.toLowerCase())||t.phone.includes(cari.replace(/\D/g,'')));
 function edit(t?:Guest){setEditing(t??null);setNama(t?.full_name??'');setAlamat(t?.address??'');setTelepon(t?.phone??'');setCatatan(t?.notes??'');setMessage('');setOpen(true)}
 async function save(e:React.FormEvent){e.preventDefault();const match=rows.find(t=>t.phone===telepon.trim()&&t.id!==editing?.id);if(match){setMessage(`Nomor sudah tercatat atas nama ${match.full_name}. Gunakan data tamu tersebut.`);return;}if(!/^[0-9+]{8,16}$/.test(telepon.trim())){setMessage('Nomor HP harus 8–16 digit.');return;}const payload={full_name:nama.trim(),address:alamat.trim(),phone:telepon.trim(),notes:catatan};const result=editing?await supabase.from('guests').update(payload).eq('id',editing.id):await supabase.from('guests').insert(payload);if(result.error)setMessage(result.error.code==='23505'?'Nomor HP sudah tercatat. Gunakan data tamu tersebut.':result.error.message);else{setOpen(false);await refresh()}}
 return <Kerangka judul="Tamu" keterangan={`${rows.length} tamu tercatat`} aksi={<Button className="h-11 rounded-xl" onClick={()=>edit()}>Tambah</Button>}><KotakCari value={cari} onChange={setCari} placeholder="Cari nama atau nomor HP"/>{loading&&<p className="mt-4 text-sm">Memuat tamu…</p>}{error&&<p role="alert" className="mt-4 text-sm text-destructive">{error}</p>}<div className="mt-4"><Daftar>{hasil.map(t=><li key={t.id} className="flex items-center gap-3 px-4 py-3.5"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-full bg-primary-soft text-sm font-bold text-primary">{t.full_name[0]}</span><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{t.full_name}</p><p className="text-xs text-muted-foreground">{t.phone} · {t.address}</p></div><Button size="sm" variant="outline" onClick={()=>edit(t)}>Ubah</Button></li>)}</Daftar>{!loading&&!hasil.length&&<p className="mt-8 text-center text-sm text-muted-foreground">Tamu tidak ditemukan.</p>}</div>{open&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-foreground/30 p-4"><form onSubmit={save} className="w-full max-w-md space-y-3 rounded-2xl bg-background p-5 shadow-lembut"><h2 className="text-lg font-bold">{editing?'Ubah tamu':'Tambah tamu'}</h2>{[['Nama lengkap',nama,setNama],['Alamat',alamat,setAlamat],['Nomor HP/WhatsApp',telepon,setTelepon],['Catatan',catatan,setCatatan]].map(([label,value,setter])=><label key={label as string} className="block text-sm">{label as string}<input required={label!=='Catatan'} value={value as string} onChange={e=>(setter as (s:string)=>void)(e.target.value)} className="mt-1 h-11 w-full rounded-xl border border-input bg-background px-3"/></label>)}{message&&<p role="alert" className="text-sm text-destructive">{message}</p>}<div className="flex justify-end gap-2"><Button type="button" variant="outline" onClick={()=>setOpen(false)}>Batal</Button><Button type="submit">Simpan</Button></div></form></div>}</Kerangka>}
