import { createFileRoute } from '@tanstack/react-router';
import { useState } from 'react';
import { Kerangka, Daftar } from '@/components/kerangka';
import { Button } from '@/components/ui/button';
import { useTable, type RoomType } from '@/lib/data-live';
import { supabase } from '@/integrations/supabase/client';
import { meta } from '@/lib/meta';
export const Route=createFileRoute('/tipe-kamar')({head:()=>meta('Tipe Kamar','Pengelolaan tipe kamar Baturaden 25 Homestay.'),component:Halaman});
function Halaman(){const {rows,refresh,error}=useTable('room_types');const [item,setItem]=useState<RoomType|null>(null);const [open,setOpen]=useState(false);const [nama,setNama]=useState('');const [deskripsi,setDeskripsi]=useState('');const [active,setActive]=useState(true);const [message,setMessage]=useState('');function edit(t?:RoomType){setItem(t??null);setNama(t?.name??'');setDeskripsi(t?.description??'');setActive(t?.active??true);setMessage('');setOpen(true)}async function save(e:React.FormEvent){e.preventDefault();const payload={name:nama.trim(),description:deskripsi,active};const result=item?await supabase.from('room_types').update(payload).eq('id',item.id):await supabase.from('room_types').insert(payload);if(result.error)setMessage(result.error.message);else{setOpen(false);await refresh()}}
 return <Kerangka judul="Tipe Kamar" aksi={<Button onClick={()=>edit()}>Tambah</Button>}>{error&&<p role="alert">{error}</p>}<Daftar>{rows.map(t=><li key={t.id} className="flex items-center gap-3 px-4 py-4"><div className="flex-1"><p className="font-semibold">{t.name}</p><p className="text-xs text-muted-foreground">{t.description} · {t.active?'Aktif':'Tidak aktif'}</p></div><Button size="sm" variant="outline" onClick={()=>edit(t)}>Ubah</Button></li>)}</Daftar>{open&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-foreground/30 p-4"><form onSubmit={save} className="w-full max-w-md space-y-3 rounded-2xl bg-background p-5 shadow-lembut"><h2 className="text-lg font-bold">{item?'Ubah tipe kamar':'Tambah tipe kamar'}</h2><label className="block text-sm">Nama<input required value={nama} onChange={e=>setNama(e.target.value)} className="mt-1 h-11 w-full rounded-xl border border-input bg-background px-3"/></label><label className="block text-sm">Deskripsi<input value={deskripsi} onChange={e=>setDeskripsi(e.target.value)} className="mt-1 h-11 w-full rounded-xl border border-input bg-background px-3"/></label><label className="flex gap-2 text-sm"><input type="checkbox" checked={active} onChange={e=>setActive(e.target.checked)}/>Aktif</label>{message&&<p role="alert">{message}</p>}<div className="flex justify-end gap-2"><Button type="button" variant="outline" onClick={()=>setOpen(false)}>Batal</Button><Button>Simpan</Button></div></form></div>}</Kerangka>}
