CREATE TYPE public.app_role AS ENUM ('owner','employee');
CREATE TYPE public.employee_position AS ENUM ('receptionist','housekeeping');
CREATE TYPE public.room_status AS ENUM ('ready','occupied','dirty','cleaning');
CREATE TYPE public.transaction_status AS ENUM ('booking','check_in','check_out','cancelled');
CREATE TABLE public.user_roles (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL UNIQUE, role public.app_role NOT NULL);
GRANT SELECT ON public.user_roles TO authenticated;
GRANT ALL ON public.user_roles TO service_role;
ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;
CREATE POLICY role_self_read ON public.user_roles FOR SELECT TO authenticated USING (user_id = auth.uid());
CREATE TABLE public.employees (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid UNIQUE NOT NULL, name text NOT NULL CHECK (length(trim(name)) > 0), employee_id text UNIQUE NOT NULL CHECK (length(trim(employee_id)) > 0), position public.employee_position NOT NULL, active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT ON public.employees TO authenticated;
GRANT ALL ON public.employees TO service_role;
ALTER TABLE public.employees ENABLE ROW LEVEL SECURITY;
CREATE FUNCTION public.has_role(_user_id uuid, _role public.app_role) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$ SELECT EXISTS (SELECT 1 FROM public.user_roles WHERE user_id = _user_id AND role = _role) $$;
REVOKE ALL ON FUNCTION public.has_role(uuid, public.app_role) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.has_role(uuid, public.app_role) TO authenticated, service_role;
CREATE FUNCTION public.can_operate(_user_id uuid) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$ SELECT public.has_role(_user_id, 'owner') OR (public.has_role(_user_id, 'employee') AND EXISTS (SELECT 1 FROM public.employees WHERE user_id = _user_id AND active)) $$;
REVOKE ALL ON FUNCTION public.can_operate(uuid) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.can_operate(uuid) TO authenticated, service_role;
CREATE FUNCTION public.is_receptionist(_user_id uuid) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$ SELECT public.has_role(_user_id, 'employee') AND EXISTS (SELECT 1 FROM public.employees WHERE user_id = _user_id AND active AND position = 'receptionist') $$;
REVOKE ALL ON FUNCTION public.is_receptionist(uuid) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.is_receptionist(uuid) TO authenticated, service_role;
CREATE POLICY employee_owner_read ON public.employees FOR SELECT TO authenticated USING (public.has_role(auth.uid(), 'owner') OR (user_id = auth.uid() AND public.can_operate(auth.uid())));
CREATE TABLE public.room_types (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text UNIQUE NOT NULL CHECK (length(trim(name)) > 0), description text NOT NULL DEFAULT '', active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT, INSERT, UPDATE, DELETE ON public.room_types TO authenticated;
GRANT ALL ON public.room_types TO service_role;
ALTER TABLE public.room_types ENABLE ROW LEVEL SECURITY;
CREATE POLICY room_types_read ON public.room_types FOR SELECT TO authenticated USING (public.can_operate(auth.uid()));
CREATE POLICY room_types_write ON public.room_types FOR ALL TO authenticated USING (public.has_role(auth.uid(), 'owner')) WITH CHECK (public.has_role(auth.uid(), 'owner'));
CREATE TABLE public.rooms (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), room_number text UNIQUE NOT NULL CHECK (length(trim(room_number)) > 0), room_type_id uuid NOT NULL REFERENCES public.room_types(id), base_price numeric(12,2) NOT NULL DEFAULT 0 CHECK (base_price >= 0), status public.room_status NOT NULL DEFAULT 'ready', notes text NOT NULL DEFAULT '', active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT, INSERT, UPDATE, DELETE ON public.rooms TO authenticated;
GRANT ALL ON public.rooms TO service_role;
ALTER TABLE public.rooms ENABLE ROW LEVEL SECURITY;
CREATE POLICY rooms_read ON public.rooms FOR SELECT TO authenticated USING (public.can_operate(auth.uid()));
CREATE POLICY rooms_write ON public.rooms FOR ALL TO authenticated USING (public.has_role(auth.uid(), 'owner')) WITH CHECK (public.has_role(auth.uid(), 'owner'));
CREATE FUNCTION public.validate_room_transition() RETURNS trigger LANGUAGE plpgsql SET search_path = public AS $$ BEGIN IF NEW.status <> OLD.status AND NOT ((OLD.status = 'ready' AND NEW.status = 'occupied') OR (OLD.status = 'occupied' AND NEW.status = 'dirty') OR (OLD.status = 'dirty' AND NEW.status = 'cleaning') OR (OLD.status = 'cleaning' AND NEW.status = 'ready')) THEN RAISE EXCEPTION 'Perubahan status kamar tidak sesuai urutan'; END IF; RETURN NEW; END $$;
CREATE TRIGGER room_transition BEFORE UPDATE ON public.rooms FOR EACH ROW EXECUTE FUNCTION public.validate_room_transition();
CREATE TABLE public.packages (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text UNIQUE NOT NULL CHECK (length(trim(name)) > 0), duration_minutes integer NOT NULL CHECK (duration_minutes > 0), price numeric(12,2) NOT NULL CHECK (price >= 0), active boolean NOT NULL DEFAULT true, description text NOT NULL DEFAULT '', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT, INSERT, UPDATE, DELETE ON public.packages TO authenticated;
GRANT ALL ON public.packages TO service_role;
ALTER TABLE public.packages ENABLE ROW LEVEL SECURITY;
CREATE POLICY packages_read ON public.packages FOR SELECT TO authenticated USING (public.can_operate(auth.uid()));
CREATE POLICY packages_write ON public.packages FOR ALL TO authenticated USING (public.has_role(auth.uid(), 'owner')) WITH CHECK (public.has_role(auth.uid(), 'owner'));
CREATE TABLE public.package_price_history (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), package_id uuid NOT NULL REFERENCES public.packages(id), old_price numeric(12,2) NOT NULL, new_price numeric(12,2) NOT NULL, reason text NOT NULL DEFAULT '', changed_by uuid, changed_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT ON public.package_price_history TO authenticated;
GRANT ALL ON public.package_price_history TO service_role;
ALTER TABLE public.package_price_history ENABLE ROW LEVEL SECURITY;
CREATE POLICY price_history_owner_read ON public.package_price_history FOR SELECT TO authenticated USING (public.has_role(auth.uid(), 'owner'));
CREATE TABLE public.guests (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), full_name text NOT NULL CHECK (length(trim(full_name)) > 0), address text NOT NULL CHECK (length(trim(address)) > 0), phone text UNIQUE NOT NULL CHECK (phone ~ '^[0-9+]{8,16}$'), notes text NOT NULL DEFAULT '', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT, INSERT, UPDATE, DELETE ON public.guests TO authenticated;
GRANT ALL ON public.guests TO service_role;
ALTER TABLE public.guests ENABLE ROW LEVEL SECURITY;
CREATE POLICY guests_read ON public.guests FOR SELECT TO authenticated USING (public.has_role(auth.uid(), 'owner') OR public.is_receptionist(auth.uid()));
CREATE POLICY guests_write ON public.guests FOR ALL TO authenticated USING (public.has_role(auth.uid(), 'owner') OR public.is_receptionist(auth.uid())) WITH CHECK (public.has_role(auth.uid(), 'owner') OR public.is_receptionist(auth.uid()));
CREATE SEQUENCE public.transaction_number_seq START 1;
GRANT USAGE ON SEQUENCE public.transaction_number_seq TO authenticated, service_role;
CREATE TABLE public.transactions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), transaction_number text UNIQUE NOT NULL DEFAULT ('BTRD25-' || lpad(nextval('public.transaction_number_seq')::text, 6, '0')), guest_id uuid NOT NULL REFERENCES public.guests(id), room_id uuid NOT NULL REFERENCES public.rooms(id), status public.transaction_status NOT NULL DEFAULT 'booking', created_by uuid NOT NULL DEFAULT auth.uid(), price_snapshot numeric(12,2) CHECK (price_snapshot >= 0), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), CONSTRAINT transaction_number_format CHECK (transaction_number ~ '^BTRD25-[0-9]{6}$'));
GRANT SELECT ON public.transactions TO authenticated;
GRANT ALL ON public.transactions TO service_role;
ALTER TABLE public.transactions ENABLE ROW LEVEL SECURITY;
CREATE POLICY transactions_read ON public.transactions FOR SELECT TO authenticated USING (public.has_role(auth.uid(), 'owner') OR public.is_receptionist(auth.uid()));
CREATE FUNCTION public.protect_transaction_number() RETURNS trigger LANGUAGE plpgsql SET search_path = public AS $$ BEGIN IF NEW.transaction_number <> OLD.transaction_number OR NEW.guest_id <> OLD.guest_id OR NEW.created_by <> OLD.created_by THEN RAISE EXCEPTION 'Identitas transaksi tidak dapat diubah'; END IF; RETURN NEW; END $$;
CREATE TRIGGER transaction_identity BEFORE UPDATE ON public.transactions FOR EACH ROW EXECUTE FUNCTION public.protect_transaction_number();
CREATE TABLE public.activity_logs (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid, action text NOT NULL, entity_type text NOT NULL, entity_id uuid, description text NOT NULL DEFAULT '', created_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT ON public.activity_logs TO authenticated;
GRANT ALL ON public.activity_logs TO service_role;
ALTER TABLE public.activity_logs ENABLE ROW LEVEL SECURITY;
CREATE POLICY logs_owner_read ON public.activity_logs FOR SELECT TO authenticated USING (public.has_role(auth.uid(), 'owner'));
CREATE FUNCTION public.audit_changes() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$ DECLARE actor uuid; BEGIN actor := auth.uid(); IF TG_TABLE_NAME = 'packages' AND TG_OP = 'UPDATE' AND OLD.price IS DISTINCT FROM NEW.price THEN INSERT INTO public.package_price_history(package_id, old_price, new_price, reason, changed_by) VALUES (NEW.id, OLD.price, NEW.price, COALESCE(NULLIF(current_setting('app.price_reason', true), ''), 'Perubahan harga'), actor); END IF; IF TG_OP = 'INSERT' THEN INSERT INTO public.activity_logs(user_id, action, entity_type, entity_id, description) VALUES (actor, 'buat', TG_TABLE_NAME, NEW.id, 'Data dibuat'); ELSE INSERT INTO public.activity_logs(user_id, action, entity_type, entity_id, description) VALUES (actor, 'ubah', TG_TABLE_NAME, NEW.id, 'Data diubah'); END IF; RETURN NEW; END $$;
CREATE TRIGGER audit_room_types AFTER INSERT OR UPDATE ON public.room_types FOR EACH ROW EXECUTE FUNCTION public.audit_changes();
CREATE TRIGGER audit_rooms AFTER INSERT OR UPDATE ON public.rooms FOR EACH ROW EXECUTE FUNCTION public.audit_changes();
CREATE TRIGGER audit_packages AFTER INSERT OR UPDATE ON public.packages FOR EACH ROW EXECUTE FUNCTION public.audit_changes();
CREATE TRIGGER audit_guests AFTER INSERT OR UPDATE ON public.guests FOR EACH ROW EXECUTE FUNCTION public.audit_changes();
CREATE TRIGGER audit_employees AFTER INSERT OR UPDATE ON public.employees FOR EACH ROW EXECUTE FUNCTION public.audit_changes();
CREATE TRIGGER audit_transactions AFTER INSERT OR UPDATE ON public.transactions FOR EACH ROW EXECUTE FUNCTION public.audit_changes();
CREATE FUNCTION public.touch_updated_at() RETURNS trigger LANGUAGE plpgsql SET search_path = public AS $$ BEGIN NEW.updated_at := now(); RETURN NEW; END $$;
CREATE TRIGGER touch_room_types BEFORE UPDATE ON public.room_types FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at();
CREATE TRIGGER touch_rooms BEFORE UPDATE ON public.rooms FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at();
CREATE TRIGGER touch_packages BEFORE UPDATE ON public.packages FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at();
CREATE TRIGGER touch_guests BEFORE UPDATE ON public.guests FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at();
CREATE TRIGGER touch_employees BEFORE UPDATE ON public.employees FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at();
CREATE TRIGGER touch_transactions BEFORE UPDATE ON public.transactions FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at();