/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as CheckInRouteImport } from './routes/check-in'
import { Route as HousekeepingRouteImport } from './routes/housekeeping'
import { Route as KamarRouteImport } from './routes/kamar'
import { Route as KaryawanRouteImport } from './routes/karyawan'
import { Route as KeuanganRouteImport } from './routes/keuangan'
import { Route as PaketRouteImport } from './routes/paket'
import { Route as PengaturanRouteImport } from './routes/pengaturan'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as TamuRouteImport } from './routes/tamu'
import { Route as TipeKamarRouteImport } from './routes/tipe-kamar'
import { Route as TransaksiRouteImport } from './routes/transaksi'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckInRoute = CheckInRouteImport.update({
  id: '/check-in',
  path: '/check-in',
  getParentRoute: () => rootRouteImport,
} as any)
const HousekeepingRoute = HousekeepingRouteImport.update({
  id: '/housekeeping',
  path: '/housekeeping',
  getParentRoute: () => rootRouteImport,
} as any)
const KamarRoute = KamarRouteImport.update({
  id: '/kamar',
  path: '/kamar',
  getParentRoute: () => rootRouteImport,
} as any)
const KaryawanRoute = KaryawanRouteImport.update({
  id: '/karyawan',
  path: '/karyawan',
  getParentRoute: () => rootRouteImport,
} as any)
const KeuanganRoute = KeuanganRouteImport.update({
  id: '/keuangan',
  path: '/keuangan',
  getParentRoute: () => rootRouteImport,
} as any)
const PaketRoute = PaketRouteImport.update({
  id: '/paket',
  path: '/paket',
  getParentRoute: () => rootRouteImport,
} as any)
const PengaturanRoute = PengaturanRouteImport.update({
  id: '/pengaturan',
  path: '/pengaturan',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TamuRoute = TamuRouteImport.update({
  id: '/tamu',
  path: '/tamu',
  getParentRoute: () => rootRouteImport,
} as any)
const TipeKamarRoute = TipeKamarRouteImport.update({
  id: '/tipe-kamar',
  path: '/tipe-kamar',
  getParentRoute: () => rootRouteImport,
} as any)
const TransaksiRoute = TransaksiRouteImport.update({
  id: '/transaksi',
  path: '/transaksi',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/booking': typeof BookingRoute
  '/check-in': typeof CheckInRoute
  '/housekeeping': typeof HousekeepingRoute
  '/kamar': typeof KamarRoute
  '/karyawan': typeof KaryawanRoute
  '/keuangan': typeof KeuanganRoute
  '/paket': typeof PaketRoute
  '/pengaturan': typeof PengaturanRoute
  '/reset-password': typeof ResetPasswordRoute
  '/tamu': typeof TamuRoute
  '/tipe-kamar': typeof TipeKamarRoute
  '/transaksi': typeof TransaksiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/booking': typeof BookingRoute
  '/check-in': typeof CheckInRoute
  '/housekeeping': typeof HousekeepingRoute
  '/kamar': typeof KamarRoute
  '/karyawan': typeof KaryawanRoute
  '/keuangan': typeof KeuanganRoute
  '/paket': typeof PaketRoute
  '/pengaturan': typeof PengaturanRoute
  '/reset-password': typeof ResetPasswordRoute
  '/tamu': typeof TamuRoute
  '/tipe-kamar': typeof TipeKamarRoute
  '/transaksi': typeof TransaksiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/booking': typeof BookingRoute
  '/check-in': typeof CheckInRoute
  '/housekeeping': typeof HousekeepingRoute
  '/kamar': typeof KamarRoute
  '/karyawan': typeof KaryawanRoute
  '/keuangan': typeof KeuanganRoute
  '/paket': typeof PaketRoute
  '/pengaturan': typeof PengaturanRoute
  '/reset-password': typeof ResetPasswordRoute
  '/tamu': typeof TamuRoute
  '/tipe-kamar': typeof TipeKamarRoute
  '/transaksi': typeof TransaksiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/booking'
    | '/check-in'
    | '/housekeeping'
    | '/kamar'
    | '/karyawan'
    | '/keuangan'
    | '/paket'
    | '/pengaturan'
    | '/reset-password'
    | '/tamu'
    | '/tipe-kamar'
    | '/transaksi'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/booking'
    | '/check-in'
    | '/housekeeping'
    | '/kamar'
    | '/karyawan'
    | '/keuangan'
    | '/paket'
    | '/pengaturan'
    | '/reset-password'
    | '/tamu'
    | '/tipe-kamar'
    | '/transaksi'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/booking'
    | '/check-in'
    | '/housekeeping'
    | '/kamar'
    | '/karyawan'
    | '/keuangan'
    | '/paket'
    | '/pengaturan'
    | '/reset-password'
    | '/tamu'
    | '/tipe-kamar'
    | '/transaksi'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BookingRoute: typeof BookingRoute
  CheckInRoute: typeof CheckInRoute
  HousekeepingRoute: typeof HousekeepingRoute
  KamarRoute: typeof KamarRoute
  KaryawanRoute: typeof KaryawanRoute
  KeuanganRoute: typeof KeuanganRoute
  PaketRoute: typeof PaketRoute
  PengaturanRoute: typeof PengaturanRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TamuRoute: typeof TamuRoute
  TipeKamarRoute: typeof TipeKamarRoute
  TransaksiRoute: typeof TransaksiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check-in': {
      id: '/check-in'
      path: '/check-in'
      fullPath: '/check-in'
      preLoaderRoute: typeof CheckInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/housekeeping': {
      id: '/housekeeping'
      path: '/housekeeping'
      fullPath: '/housekeeping'
      preLoaderRoute: typeof HousekeepingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kamar': {
      id: '/kamar'
      path: '/kamar'
      fullPath: '/kamar'
      preLoaderRoute: typeof KamarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/karyawan': {
      id: '/karyawan'
      path: '/karyawan'
      fullPath: '/karyawan'
      preLoaderRoute: typeof KaryawanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keuangan': {
      id: '/keuangan'
      path: '/keuangan'
      fullPath: '/keuangan'
      preLoaderRoute: typeof KeuanganRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paket': {
      id: '/paket'
      path: '/paket'
      fullPath: '/paket'
      preLoaderRoute: typeof PaketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pengaturan': {
      id: '/pengaturan'
      path: '/pengaturan'
      fullPath: '/pengaturan'
      preLoaderRoute: typeof PengaturanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tamu': {
      id: '/tamu'
      path: '/tamu'
      fullPath: '/tamu'
      preLoaderRoute: typeof TamuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tipe-kamar': {
      id: '/tipe-kamar'
      path: '/tipe-kamar'
      fullPath: '/tipe-kamar'
      preLoaderRoute: typeof TipeKamarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transaksi': {
      id: '/transaksi'
      path: '/transaksi'
      fullPath: '/transaksi'
      preLoaderRoute: typeof TransaksiRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BookingRoute: BookingRoute,
  CheckInRoute: CheckInRoute,
  HousekeepingRoute: HousekeepingRoute,
  KamarRoute: KamarRoute,
  KaryawanRoute: KaryawanRoute,
  KeuanganRoute: KeuanganRoute,
  PaketRoute: PaketRoute,
  PengaturanRoute: PengaturanRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TamuRoute: TamuRoute,
  TipeKamarRoute: TipeKamarRoute,
  TransaksiRoute: TransaksiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
